<?php

namespace Database\Seeders;

use DB;
use Illuminate\Support\Str;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'title' => 'Проект дома "Маршак"',
                'img' => '/tmp_data/projects/pr_1/p1_main.jpeg',
                'slug' => 'proekt-doma-marshak',
                'start_price' => 5990000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_1/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_1/p1_photo_1.jpeg',
                    '/tmp_data/projects/pr_1/p1_photo_2.jpeg',
                    '/tmp_data/projects/pr_1/p1_photo_3.jpeg',
                    '/tmp_data/projects/pr_1/p1_photo_4.jpeg'
                ],
                'layout' => [
                    '/tmp_data/projects/pr_1/p1_plan_1.jpeg',
                ],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 68,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный фундамент',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,4 x 8,7 м',
                'extension' => null,

            ],
            [
                'title' => 'Проект дома  "Блок"',
                'img' => '/tmp_data/projects/pr_2/p2_photo_1.JPG',
                'slug' => 'proekt-doma-blok',
                'start_price' => 7300000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_2/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_2/p2_photo_1.JPG',
                    '/tmp_data/projects/pr_2/p2_photo_2.JPG',
                    '/tmp_data/projects/pr_2/p2_photo_3.JPG',
                    '/tmp_data/projects/pr_2/p2_photo_4.JPG',
                    '/tmp_data/projects/pr_2/p2_photo_5.JPG',

                ],
                'layout' => [
                    '/tmp_data/projects/pr_2/p2_photo_6.JPG',
                ],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 80,
                'wall_material' => null,
                'foundation' => 'Плитный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '11 x 9,9 м',
                'extension' => null,
            ],

            [
                'title' => 'Проект дома "Идилия"',
                'img' => '/tmp_data/projects/pr_3/p3_photo_1.JPG',
                'slug' => 'proekt-doma-idiliya',
                'start_price' => 6500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_3/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_3/p3_photo_1.JPG',
                    '/tmp_data/projects/pr_3/p3_photo_2.JPG',
                    '/tmp_data/projects/pr_3/p3_photo_3.JPG',
                    '/tmp_data/projects/pr_3/p3_photo_4.JPG',
                    '/tmp_data/projects/pr_3/p3_photo_5.JPG',

                ],
                'layout' => [
                    '/tmp_data/projects/pr_3/p3_photo_6.JPG',
                ],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 94,
                'wall_material' => null,
                'foundation' => '',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => true,
                'plan_dimensions' => '8,8 x 6,8 м',
                'extension' => 'Терасса',
            ],

            [
                'title' => 'Проект дома "Мечта поэта"',
                'img' => '/tmp_data/projects/pr_4/p4_photo_1.JPG',
                'slug' => 'proekt-doma-mechta-poeta',
                'start_price' => 8500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_4/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_4/p4_photo_1.JPG',
                    '/tmp_data/projects/pr_4/p4_photo_2.JPG',
                    '/tmp_data/projects/pr_4/p4_photo_3.JPG',
                    '/tmp_data/projects/pr_4/p4_photo_4.JPG',
                    '/tmp_data/projects/pr_4/p4_photo_5.JPG',
                    '/tmp_data/projects/pr_4/p4_photo_6.JPG',
                    '/tmp_data/projects/pr_4/p4_photo_7.JPG',
                ],
                'layout' => [
                    '/tmp_data/projects/pr_4/p4_photo_8.JPG',
                ],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 98,
                'wall_material' => 'Пеноблок',
                'foundation' => '',
                'ceiling_height' => 2.5,
                'flooring' => "Деревянные перекрытия",
                'mansard' => true,
                'plan_dimensions' => '7,6 x 7,9 м',
                'extension' => null,
            ],

            [
                'title' => 'Дом каркасный серии "Барнэо" ',
                'img' => '/tmp_data/projects/pr_5/p5_photo_1.JPG',
                'slug' => 'dom-karkasnyi-serii-barn-ploshhadiu-94-kvm',
                'start_price' => 8500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_5/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_5/p5_photo_1.JPG',
                    '/tmp_data/projects/pr_5/p5_photo_2.JPG',
                ],
                'layout' => [
                    '/tmp_data/projects/pr_5/p5_photo_3.JPG',
                ],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 94,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => 'Деревянные балки',
                'mansard' => false,
                'plan_dimensions' => '6,9 x 7,2 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом каркасный серии "Барнe" ',
                'img' => '/tmp_data/projects/pr_6/p6_photo_1.JPG',
                'slug' => 'dom-karkasnyi-serii-barne-ploshhadiu-80-kvm',
                'start_price' => 8000000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_6/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_6/p6_photo_1.JPG',
                    '/tmp_data/projects/pr_6/p6_photo_2.JPG',
                    '/tmp_data/projects/pr_6/p6_photo_3.JPG',
                    '/tmp_data/projects/pr_6/p6_photo_4.JPG',
                ],
                'layout' => [
                    '/tmp_data/projects/pr_6/p6_photo_5.JPG',
                ],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 80,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '10,5 x 8,5 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом каркасный серии "Барне" площадью 100 кв.м.',
                'img' => '/tmp_data/projects/pr_7/p7_photo_1.JPG',
                'slug' => 'dom-karkasnyi-serii-barnе-ploshhadiu-100-kvm',
                'start_price' => 9000000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_7/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_7/p7_photo_1.JPG',
                    '/tmp_data/projects/pr_7/p7_photo_2.JPG',
                    '/tmp_data/projects/pr_7/p7_photo_3.JPG',
                    '/tmp_data/projects/pr_7/p7_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_7/p7_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 100,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '12,2 x 9,2 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом серии «Гармония» площадью 80 кв.м.',
                'img' => '/tmp_data/projects/pr_8/p8_photo_1.JPG',
                'slug' => 'dom-serii-garmoniya-ploshhadiu-80-kvm',
                'start_price' => 7800000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_8/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_8/p8_photo_1.JPG',
                    '/tmp_data/projects/pr_8/p8_photo_2.JPG',
                    '/tmp_data/projects/pr_8/p8_photo_3.JPG',
                    '/tmp_data/projects/pr_8/p8_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_8/p8_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 80,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,9 x 11,02 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом серии «Гармония» площадью 68 кв.м.',
                'img' => '/tmp_data/projects/pr_9/p9_photo_1.JPG',
                'slug' => 'dom-serii-garmoniya-ploshhadiu-68-kvm',
                'start_price' => 7400000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_9/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_9/p9_photo_1.JPG',
                    '/tmp_data/projects/pr_9/p9_photo_2.JPG',
                    '/tmp_data/projects/pr_9/p9_photo_3.JPG',
                    '/tmp_data/projects/pr_9/p9_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_9/p9_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 68,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,4 x 8,7 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом серии «Гармония» площадью 60 кв.м.',
                'img' => '/tmp_data/projects/pr_10/p10_photo_1.JPG',
                'slug' => 'dom-serii-garmoniya-ploshhadiu-60-kvm',
                'start_price' => 6800000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_10/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_10/p10_photo_1.JPG',
                    '/tmp_data/projects/pr_10/p10_photo_2.JPG',
                    '/tmp_data/projects/pr_10/p10_photo_3.JPG',
                    '/tmp_data/projects/pr_10/p10_photo_4.JPG',
                    '/tmp_data/projects/pr_10/p10_photo_5.JPG',
                    '/tmp_data/projects/pr_10/p10_photo_6.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_10/p10_photo_7.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 60,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '10 x 6 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом серии «Гармония» площадью 110 кв.м.',
                'img' => '/tmp_data/projects/pr_11/p11_photo_1.JPG',
                'slug' => 'dom-serii-garmoniya-ploshhadiu-110-kvm',
                'start_price' => 9500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_11/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_11/p11_photo_1.JPG',
                    '/tmp_data/projects/pr_11/p11_photo_2.JPG',
                    '/tmp_data/projects/pr_11/p11_photo_3.JPG',
                    '/tmp_data/projects/pr_11/p11_photo_4.JPG',
                    '/tmp_data/projects/pr_11/p11_photo_5.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_11/p11_photo_6.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 110,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => "Перекрытия",
                'mansard' => false,
                'plan_dimensions' => '9,0 x 7,9 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом "Роща"',
                'img' => '/tmp_data/projects/pr_12/p12_photo_1.JPG',
                'slug' => 'dom-rosha',
                'start_price' => 9450000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_12/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_12/p12_photo_1.JPG',
                    '/tmp_data/projects/pr_12/p12_photo_2.JPG',
                    '/tmp_data/projects/pr_12/p12_photo_3.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_12/p12_photo_4.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 126,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '13,6 x 11,4 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом "Горизонт"',
                'img' => '/tmp_data/projects/pr_13/p13_photo_1.JPG',
                'slug' => 'dom-gorizont',
                'start_price' => 10000000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_13/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_13/p13_photo_1.JPG',
                    '/tmp_data/projects/pr_13/p13_photo_2.JPG',
                    '/tmp_data/projects/pr_13/p13_photo_3.JPG',
                    '/tmp_data/projects/pr_13/p13_photo_4.JPG',
                    '/tmp_data/projects/pr_13/p13_photo_5.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_13/p13_photo_6.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 127,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '10,9 x 7,8 м',
                'extension' => null,
            ],
            [
                'title' => 'Индивидуальный каркасный дом KD-109',
                'img' => '/tmp_data/projects/pr_14/p14_photo_1.JPG',
                'slug' => 'individualnyi-karkasnyi-dom-kd-109',
                'start_price' => 3870000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_14/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_14/p14_photo_1.JPG',
                    '/tmp_data/projects/pr_14/p14_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_14/p14_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 43,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7,8 x 5,6 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом "Родник"',
                'img' => '/tmp_data/projects/pr_15/p15_photo_1.JPG',
                'slug' => 'dom-rodnik',
                'start_price' => 8300000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_15/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_15/p15_photo_1.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_15/p15_photo_2.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 104,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Свайный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '10,3 x 8,3 м',
                'extension' => null,
            ],
            [
                'title' => 'Индивидуальный каркасный дом KD-110',
                'img' => '/tmp_data/projects/pr_16/p16_photo_1.JPG',
                'slug' => 'individualnyi-karkasnyi-dom-kd-110',
                'start_price' => 8190000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_16/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_16/p16_photo_1.JPG',
                    '/tmp_data/projects/pr_16/p16_photo_2.JPG',
                    '/tmp_data/projects/pr_16/p16_photo_3.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_16/p16_photo_4.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 91,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '8,035 x 13,7 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Индивидуальный каркасный дом KD-111',
                'img' => '/tmp_data/projects/pr_17/p17_photo_1.JPG',
                'slug' => 'individualnyi-karkasnyi-dom-kd-111',
                'start_price' => 8640000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_17/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_17/p17_photo_1.JPG',
                    '/tmp_data/projects/pr_17/p17_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_17/p17_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 962,
                'wall_material' => 'Кирпич',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,7 x 10,8 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Индивидуальный каркасный дом KD-112',
                'img' => '/tmp_data/projects/pr_18/p18_photo_1.JPG',
                'slug' => 'individualnyi-karkasnyi-dom-kd-112',
                'start_price' => 10440000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_18/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_18/p18_photo_1.JPG',
                    '/tmp_data/projects/pr_18/p18_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_18/p18_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 116,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,0 x 15,0 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Индивидуальный каркасный дом KD-113',
                'img' => '/tmp_data/projects/pr_19/p19_photo_1.JPG',
                'slug' => 'individualnyi-karkasnyi-dom-kd-113',
                'start_price' => 9540000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_19/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_19/p19_photo_1.JPG',
                    '/tmp_data/projects/pr_19/p19_photo_3.JPG',
                    '/tmp_data/projects/pr_19/p19_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_19/p19_photo_2.JPG',],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 106,
                'wall_material' => 'Кирпич',
                'foundation' => 'Свайный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '5,8 x 8,8 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом "Луч"',
                'img' => '/tmp_data/projects/pr_20/p20_photo_1.JPG',
                'slug' => 'dom-luch',
                'start_price' => 8500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_20/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_20/p20_photo_1.JPG',
                    '/tmp_data/projects/pr_20/p20_photo_2.JPG',
                    '/tmp_data/projects/pr_20/p20_photo_3.JPG',
                    '/tmp_data/projects/pr_20/p20_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_20/p20_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 91,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '10,3 x 12,5 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом "Очаг"',
                'img' => '/tmp_data/projects/pr_21/p21_photo_1.JPG',
                'slug' => 'dom-ochag',
                'start_price' => 8500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_21/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_21/p21_photo_1.JPG',
                    '/tmp_data/projects/pr_21/p21_photo_2.JPG',
                    '/tmp_data/projects/pr_21/p21_photo_3.JPG',
                    '/tmp_data/projects/pr_21/p21_photo_4.JPG',
                    '/tmp_data/projects/pr_21/p21_photo_5.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_21/p21_photo_6.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 91,
                'wall_material' => 'Пеноблок',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,2 x 11,9 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом из газобетона "Гавань"',
                'img' => '/tmp_data/projects/pr_22/p22_photo_1.JPG',
                'slug' => 'dom-iz-gazobetona-gavan',
                'start_price' => 8500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_22/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_22/p22_photo_1.JPG',
                    '/tmp_data/projects/pr_22/p22_photo_2.JPG',
                    '/tmp_data/projects/pr_22/p22_photo_3.JPG',
                    '/tmp_data/projects/pr_22/p22_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_22/p22_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 85,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '8,8 x 7,8 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом с двумя спальнями и террасой',
                'img' => '/tmp_data/projects/pr_23/p23_photo_1.JPG',
                'slug' => 'dom-s-dvumia-spalniami-i-terrasoi',
                'start_price' => 6450000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_23/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_23/p23_photo_1.JPG',
                    '/tmp_data/projects/pr_23/p23_photo_2.JPG',
                    '/tmp_data/projects/pr_23/p23_photo_3.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_23/p23_photo_4.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 86,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7,8 x 12,7 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом одноэтажный 103м²',
                'img' => '/tmp_data/projects/pr_24/p24_photo_1.JPG',
                'slug' => 'dom-odnoetaznyi-103m2',
                'start_price' => 9785000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_24/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_24/p24_photo_1.JPG',
                    '/tmp_data/projects/pr_24/p24_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_24/p24_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 103,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7,8 x 6,8 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом одноэтажный 209м²',
                'img' => '/tmp_data/projects/pr_25/p25_photo_1.JPG',
                'slug' => 'dom-odnoetaznyi-209m2',
                'start_price' => 14475000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_25/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_25/p25_photo_1.JPG',
                    '/tmp_data/projects/pr_25/p25_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_25/p25_photo_3.JPG',],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 209,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => "Деревянное перекрытие",
                'mansard' => false,
                'plan_dimensions' => '10,8 x 8,8 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Дом одноэтажный из газобетона',
                'img' => '/tmp_data/projects/pr_26/p26_photo_1.JPG',
                'slug' => 'dom-odnoetaznyi-iz-gazobetona',
                'start_price' => 7790000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_26/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_26/p26_photo_1.JPG',
                    '/tmp_data/projects/pr_26/p26_photo_3.JPG',
                    '/tmp_data/projects/pr_26/p26_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_26/p26_photo_2.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 82,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,9 x 9,8 м',
                'extension' => null,
            ],
            [
                'title' => 'Индивидуальный одноэтажный жилой дом из газобетона',
                'img' => '/tmp_data/projects/pr_27/p27_photo_1.JPG',
                'slug' => 'individualnyi-odnoetaznyi-ziloi-dom-iz-gazobetona',
                'start_price' => 9595000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_27/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_27/p27_photo_1.JPG',
                    '/tmp_data/projects/pr_27/p27_photo_2.JPG',
                    '/tmp_data/projects/pr_27/p27_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_27/p27_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 101,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,4 x 12,6 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом одноэтажный 149м²',
                'img' => '/tmp_data/projects/pr_28/p28_photo_1.JPG',
                'slug' => 'individualnyi-odnoetaznyi-ziloi-dom-iz-gazobetona-149m2',
                'start_price' => 14155000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_28/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_28/p28_photo_1.JPG',
                    '/tmp_data/projects/pr_28/p28_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_28/p28_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 149,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '17,8 x 10,9 м',
                'extension' => null,
            ],
            [
                'title' => 'Индивидуальный двухэтажный жилой дом из газобетона',
                'img' => '/tmp_data/projects/pr_28/p28_photo_1.JPG',
                'slug' => 'individualnyi-dvuxetaznyi-ziloi-dom-iz-gazobetona',
                'start_price' => 11685000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_28/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_28/p28_photo_1.JPG',
                    '/tmp_data/projects/pr_28/p28_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_28/p28_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 123,
                'wall_material' => 'Газобетон',
                'foundation' => 'Монолитный',
                'ceiling_height' => 2.5,
                'flooring' => "Деревянное перекрытие с шумоизоляцией",
                'mansard' => false,
                'plan_dimensions' => '9,3 x 8,9 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Одноэтажный дом из бруса с террасой',
                'img' => '/tmp_data/projects/pr_29/p29_photo_1.JPG',
                'slug' => 'odnoetaznyi-dom-iz-brusa-s-terrasoi',
                'start_price' => 6570000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_29/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_29/p29_photo_1.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_29/p29_photo_2.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 73,
                'wall_material' => 'Брус',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9 x 12 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Двухэтажный дом для небольшого участка',
                'img' => '/tmp_data/projects/pr_30/p30_photo_1.JPG',
                'slug' => 'dvuxetaznyi-dom-dlia-nebolsogo-ucastka',
                'start_price' => 4575000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_30/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_30/p30_photo_1.JPG',
                    '/tmp_data/projects/pr_30/p30_photo_2.JPG',
                    '/tmp_data/projects/pr_30/p30_photo_3.JPG',
                    '/tmp_data/projects/pr_30/p30_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_30/p30_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 61,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7 x 6 м',
                'extension' => null,
            ],
            [
                'title' => 'Модульный дом площадью',
                'img' => '/tmp_data/projects/pr_31/p31_photo_1.JPG',
                'slug' => 'modulnyi-dom-ploshhadiu-30м2',
                'start_price' => 1990000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_31/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_31/p31_photo_1.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_2.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_3.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_4.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_5.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_6.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_7.JPG',
                    '/tmp_data/projects/pr_31/p31_photo_8.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_31/p31_photo_9.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 30,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Свайный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '5 x 5 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Красивый одноэтажный дом под четырехскатной крышей',
                'img' => '/tmp_data/projects/pr_32/p32_photo_1.JPG',
                'slug' => 'krasivyi-odnoetaznyi-dom-pod-cetyrexskatnoi-krysei',
                'start_price' => 5475000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_32/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_32/p32_photo_1.JPG',
                    '/tmp_data/projects/pr_32/p32_photo_2.JPG',
                    '/tmp_data/projects/pr_32/p32_photo_3.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_32/p32_photo_4.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 73,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,6 x 11,9 м',
                'extension' => null,
            ],
            [
                'title' => 'Одноэтажный коттедж',
                'img' => '/tmp_data/projects/pr_33/p33_photo_1.JPG',
                'slug' => 'odnoetaznyi-kottedz',
                'start_price' => 7650000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_33/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_33/p33_photo_1.JPG',
                    '/tmp_data/projects/pr_33/p33_photo_2.JPG',
                    '/tmp_data/projects/pr_33/p33_photo_4.JPG',
                    '/tmp_data/projects/pr_33/p33_photo_5.JPG',
                    '/tmp_data/projects/pr_33/p33_photo_6.JPG',
                    '/tmp_data/projects/pr_33/p33_photo_7.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_33/p33_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 102,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '13,5 x 9,6 м',
                'extension' => null,
            ],
            [
                'title' => 'Модульный дом площадью',
                'img' => '/tmp_data/projects/pr_34/p34_photo_1.JPG',
                'slug' => 'modulnyi-dom-ploshhadiu-60m2',
                'start_price' => 3990000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_34/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_34/p34_photo_1.JPG',
                    '/tmp_data/projects/pr_34/p34_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_34/p34_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 60,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Свайный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '6 x 5 м',
                'extension' => null,
            ],
            [
                'title' => 'Компактный дачный дом в классическом стиле',
                'img' => '/tmp_data/projects/pr_35/p35_photo_1.JPG',
                'slug' => 'kompaktnyi-dacnyi-dom-v-klassiceskom-stile',
                'start_price' => 6825000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_35/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_35/p35_photo_1.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_2.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_4.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_5.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_6.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_7.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_8.JPG',
                    '/tmp_data/projects/pr_35/p35_photo_9.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_35/p35_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 91,
                'wall_material' => 'Газобетон',
                'foundation' => 'Деревянное перекрытие',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7,1 x 8,9 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Модульный дом',
                'img' => '/tmp_data/projects/pr_36/p36_photo_1.JPG',
                'slug' => 'modulnyi-dom',
                'start_price' => 2990000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_36/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_36/p36_photo_1.JPG',
                    '/tmp_data/projects/pr_36/p36_photo_2.JPG',
                    '/tmp_data/projects/pr_36/p36_photo_3.JPG',
                    '/tmp_data/projects/pr_36/p36_photo_4.JPG',
                    '/tmp_data/projects/pr_36/p36_photo_5.JPG',
                    '/tmp_data/projects/pr_36/p36_photo_7.JPG',
                    '/tmp_data/projects/pr_36/p36_photo_8.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_36/p36_photo_6.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 45,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Свайный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,2 x 6, м',
                'extension' => null,
            ],
            [
                'title' => 'Уютный одноэтажный домик с двумя спальнями',
                'img' => '/tmp_data/projects/pr_37/p37_photo_1.JPG',
                'slug' => 'uiutnyi-odnoetaznyi-domik-s-dvumia-spalniami',
                'start_price' => 5550000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_37/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_37/p37_photo_1.JPG',
                    '/tmp_data/projects/pr_37/p37_photo_2.JPG',
                    '/tmp_data/projects/pr_37/p37_photo_4.JPG',
                    '/tmp_data/projects/pr_37/p37_photo_5.JPG',
                    '/tmp_data/projects/pr_37/p37_photo_6.JPG',
                    '/tmp_data/projects/pr_37/p37_photo_7.JPG',
                    '/tmp_data/projects/pr_37/p37_photo_8.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_37/p37_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 74,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7,7 x 11,8 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Современный дачный дом с большими окнами',
                'img' => '/tmp_data/projects/pr_38/p38_photo_1.JPG',
                'slug' => 'sovremennyi-dacnyi-dom-s-bolsimi-oknami',
                'start_price' => 4575000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_38/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_38/p38_photo_1.JPG',
                    '/tmp_data/projects/pr_38/p38_photo_2.JPG',
                    '/tmp_data/projects/pr_38/p38_photo_4.JPG',
                    '/tmp_data/projects/pr_38/p38_photo_5.JPG',
                    '/tmp_data/projects/pr_38/p38_photo_6.JPG',
                    '/tmp_data/projects/pr_38/p38_photo_7.JPG',
                    '/tmp_data/projects/pr_38/p38_photo_8.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_38/p38_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 61,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7,1 x 11 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Двухэтажный дом из бруса',
                'img' => '/tmp_data/projects/pr_39/p39_photo_1.JPG',
                'slug' => 'dvuxetaznyi-dom-iz-brusa',
                'start_price' => 10980000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_39/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_39/p39_photo_1.JPG',
                    '/tmp_data/projects/pr_39/p39_photo_2.JPG',
                    '/tmp_data/projects/pr_39/p39_photo_3.JPG',
                    '/tmp_data/projects/pr_39/p39_photo_5.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_39/p39_photo_4.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 122,
                'wall_material' => 'Брус',
                'foundation' => 'Монолитный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '16 x 13,6 м',
                'extension' => null,
            ],
            [
                'title' => 'Дом одноэтажный 149 м²',
                'img' => '/tmp_data/projects/pr_40/p40_photo_1.JPG',
                'slug' => 'dom-odnoetaznyi-149-m2',
                'start_price' => 14155000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_40/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_40/p40_photo_1.JPG',
                    '/tmp_data/projects/pr_40/p40_photo_2.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_40/p40_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 149,
                'wall_material' => 'Газобетон',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,8 x 10,8 м',
                'extension' => null,
            ],
            [
                'title' => 'Симпатичный дом в два этажа площадью 150 м2',
                'img' => '/tmp_data/projects/pr_41/p41_photo_1.JPG',
                'slug' => 'simpaticnyi-dom-v-dva-etaza-ploshhadiu-150-m2',
                'start_price' => 10950000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_41/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_41/p41_photo_1.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_2.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_4.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_5.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_6.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_7.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_8.JPG',
                    '/tmp_data/projects/pr_41/p41_photo_9.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_41/p41_photo_3.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 146,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Монолитный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '12,8 x 9,5 м',
                'extension' => null,
            ],
            [
                'title' => 'Небольшой дом квадратной формы с тремя спальнями',
                'img' => '/tmp_data/projects/pr_42/p42_photo_1.JPG',
                'slug' => 'nebolsoi-dom-kvadratnoi-formy-s-tremia-spalniami',
                'start_price' => 6000000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_42/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_42/p42_photo_1.JPG',
                    '/tmp_data/projects/pr_42/p42_photo_2.JPG',
                    '/tmp_data/projects/pr_42/p42_photo_3.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_42/p42_photo_4.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 80,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,6 x 12,4 м',
                'extension' => null,
            ],
            [
                'title' => 'Двухэтажный коттедж для узкого участка',
                'img' => '/tmp_data/projects/pr_43/p43_photo_1.JPG',
                'slug' => 'dvuxetaznyi-kottedz-dlia-uzkogo-ucastka',
                'start_price' => 6975000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_43/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_43/p43_photo_1.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_2.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_3.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_4.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_5.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_6.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_8.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_9.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_10.JPG',
                    '/tmp_data/projects/pr_43/p43_photo_11.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_43/p43_photo_7.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 93,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '13,9 x 17,2 м',
                'extension' => null,
            ],
            [
                'title' => 'Двух этажный дом',
                'img' => '/tmp_data/projects/pr_44/p44_photo_1.JPG',
                'slug' => 'dvuhetazhiy_dom',
                'start_price' => 11175000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_44/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_44/p44_photo_1.JPG',
                    '/tmp_data/projects/pr_44/p44_photo_2.JPG',
                    '/tmp_data/projects/pr_44/p44_photo_3.JPG',
                    '/tmp_data/projects/pr_44/p44_photo_4.JPG',
                    '/tmp_data/projects/pr_44/p44_photo_5.JPG',
                    '/tmp_data/projects/pr_44/p44_photo_6.JPG',
                ],
                'layout' => [],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 149,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Монолиный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '18,6 x 8,0 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Одноэтажный дом с панорамными окнами для небольшого участка',
                'img' => '/tmp_data/projects/pr_45/p45_photo_1.JPG',
                'slug' => 'odnoetaznyi-dom-s-panoramnymi-oknami-dlia-nebolsogo-ucastka',
                'start_price' => 4731650,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_45/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_45/p45_photo_1.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_45/p45_photo_2.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 77,
                'wall_material' => 'ПЩС-блоки',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9,6 x 11,3 м',
                'extension' => null,
            ],
            [
                'title' => 'Одноэтажный дом для узкого участка',
                'img' => '/tmp_data/projects/pr_46/p46_photo_1.JPG',
                'slug' => 'odnoetaznyi-dom-dlia-uzkogo-ucastka',
                'start_price' => 10500000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_46/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_46/p46_photo_1.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_2.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_3.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_4.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_5.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_6.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_8.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_9.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_10.JPG',
                    '/tmp_data/projects/pr_46/p46_photo_11.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_46/p46_photo_7.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 140,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '11,4 x 19,8 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Двухэтажный дом',
                'img' => '/tmp_data/projects/pr_47/p47_photo_1.JPG',
                'slug' => 'dvuxetaznyi-dom',
                'start_price' => 4977450,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_47/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_47/p47_photo_1.JPG',
                    '/tmp_data/projects/pr_47/p47_photo_2.JPG',
                    '/tmp_data/projects/pr_47/p47_photo_3.JPG',
                    '/tmp_data/projects/pr_47/p47_photo_4.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_47/p47_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 81,
                'wall_material' => 'ПЩС-блоки',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '7 x 8,5 м',
                'extension' => null,
            ],
            [
                'title' => 'Двухэтажный дом из бруса с балконом',
                'img' => '/tmp_data/projects/pr_48/p48_photo_1.JPG',
                'slug' => 'dvuxetaznyi-dom-iz-brusa-s-balkonom',
                'start_price' => 11610000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_48/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_48/p48_photo_1.JPG',
                    '/tmp_data/projects/pr_48/p48_photo_3.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_48/p48_photo_2.JPG'],
                'type' => 'Дом',
                'floors' => 2,
                'total_area' => 129,
                'wall_material' => 'Брус',
                'foundation' => 'Ленточный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '9 x 12 м',
                'extension' => "Терасса",
            ],
            [
                'title' => 'Одноэтажный современный каркасный дом',
                'img' => '/tmp_data/projects/pr_49/p49_photo_1.JPG',
                'slug' => 'odnoetaznyi-sovremennyi-karkasnyi-dom',
                'start_price' => 3932800,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_49/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_49/p49_photo_1.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_49/p49_photo_2.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 64,
                'wall_material' => 'ПЩС-блоки',
                'foundation' => 'Свайный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '8,8 x 6,8 м',
                'extension' => null,
            ],
            [
                'title' => 'Одноэтажный классический дом PD-214',
                'img' => '/tmp_data/projects/pr_50/p50_photo_1.JPG',
                'slug' => 'odnoetaznyi-klassiceskii-dom-pd-214',
                'start_price' => 9900000,
                'description' => file_get_contents(public_path('/tmp_data/projects/pr_50/ds.html')),
                'gallery' => [
                    '/tmp_data/projects/pr_50/p50_photo_1.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_2.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_3.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_4.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_6.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_7.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_8.JPG',
                    '/tmp_data/projects/pr_50/p50_photo_9.JPG',
                ],
                'layout' => ['/tmp_data/projects/pr_50/p50_photo_5.JPG'],
                'type' => 'Дом',
                'floors' => 1,
                'total_area' => 132,
                'wall_material' => 'СИП-панели',
                'foundation' => 'Монолитный',
                'ceiling_height' => 2.5,
                'flooring' => null,
                'mansard' => false,
                'plan_dimensions' => '11,9 x 19,9 м',
                'extension' => null,
            ]
        ];

        $i = 0;
        foreach ($data as $item) {

            $img_name = basename($item['img']);
            Storage::disk('public')->put("projects/".$img_name, file_get_contents(public_path($item['img'])), 'public');
            $item['img'] = "projects/".$img_name;

            foreach($item['gallery'] as $key => $image) {
                $img_name = basename($image);
                Storage::disk('public')->put("projects/".$img_name, file_get_contents(public_path($image)), 'public');
                $item['gallery'][$key] = "projects/".$img_name;
            }

            $item['gallery'] = json_encode($item['gallery']);

            foreach($item['layout'] as $key => $image) {
                $img_name = basename($image);
                Storage::disk('public')->put("projects/".$img_name, file_get_contents(public_path($image)), 'public');
                $item['layout'][$key] = "projects/".$img_name;
            }

            $item['layout'] = json_encode($item['layout']);

            DB::table("projects")->insert($item);


            DB::table("seo_data")->insert(
                [
                    'url' => 'projects/'.$item['slug'],
                    // 'seo_title' => $seo_data[$i]['seo_title'],
                    // 'seo_description' => $seo_data[$i]['seo_description'],
                    'seo_title' => $item['title'],
                    'seo_description' => $item['title'],
                ]
            );

            $i++;
        }


    }
}
